# Escaneo automático de dependencias con Dependabot, en busca de versiones con vulnerabilidades conocidas y opcionalmete rea PRs automáticos para actualizarlas
version: 2

# Lista de ecosistemas a monitorear
updates:
  # Configuración para npm (Node.js)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Mexico_City"
    target-branch: "main"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "security"

  # Configuración para GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Mexico_City"
    target-branch: "main"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"